import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = async name => JSON.parse(await readFile(path.join(root, 'content', `${name}.json`), 'utf8'));
const [profile, work, projects, awards, research, originalPosts] = await Promise.all(['profile', 'work', 'projects', 'achievements', 'research', 'posts'].map(read));
let imported = [];
try { imported = await read('posts-import'); } catch (e) { if (e.code !== 'ENOENT') throw e; }
const posts = [...new Map([...imported, ...originalPosts].map(p => [p.url, p])).values()].sort((a, b) => b.date.localeCompare(a.date));
const E = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const safeURL = value => { const u = new URL(value); if (!['https:', 'mailto:', 'tel:'].includes(u.protocol)) throw new Error(`Unsafe URL: ${value}`); return E(value); };
const external = (label, url, cls = '') => `<a class="${cls}" href="${safeURL(url)}">${E(label)}<span aria-hidden="true"> ↗</span></a>`;
const tags = list => list?.length ? `<ul class="tags" aria-label="Technologies">${list.map(t => `<li>${E(t)}</li>`).join('')}</ul>` : '';
const date = d => new Intl.DateTimeFormat('en', {day:'numeric', month:'short', year:'numeric', timeZone:'UTC'}).format(new Date(`${d}T00:00:00Z`));
const pages = [ ['index', 'Home'], ['about', 'About'], ['achievements', 'Achievements'], ['experience', 'Experience'], ['projects', 'Projects'], ['research', 'Research'], ['posts', 'Posts'] ];
const social = () => profile.links.map(l => external(l.label, l.url)).join('');
const sectionHead = (label, title, link, href) => `<div class="section-heading"><div><p class="eyebrow">${E(label)}</p><h2>${E(title)}</h2></div>${link ? `<a class="text-link" href="${href}">${E(link)} <span aria-hidden="true">↗</span></a>` : ''}</div>`;
const pageHead = (number, title, description = '') => `<header class="page-heading"><p class="eyebrow">${number} / ${E(profile.name)}</p><h1>${E(title)}</h1>${description ? `<p class="page-intro">${E(description)}</p>` : ''}</header>`;
const localNav = items => `<nav class="section-nav" aria-label="On this page">${items.map(([id, name]) => `<a href="#${id}">${E(name)}</a>`).join('')}</nav>`;
function photo(className = '') { return `<img class="portrait ${className}" src="assets/profile.jpeg" alt="Jaiwanth Karthi" width="560" height="518" decoding="async">`; }
function media(record) { return record.images?.length ? `<div class="media-grid">${record.images.map(i => `<img src="${E(i.src)}" alt="${E(i.alt)}" width="${Number(i.width)||640}" height="${Number(i.height)||480}" loading="lazy">`).join('')}</div>` : ''; }
function graph() {
  const layers = [[{x:40,y:66},{x:40,y:146},{x:40,y:226}], [{x:165,y:46},{x:165,y:113},{x:165,y:180},{x:165,y:247}], [{x:290,y:80},{x:290,y:146},{x:290,y:212}]];
  let lines='';
  for(let k=0;k<2;k++) layers[k].forEach((a,i)=>layers[k+1].forEach((b,j)=>{lines+=`<line data-layer="${k}" data-from="${i}" data-to="${j}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="edge"/>`;}));
  const nodes=layers.map((layer,k)=>layer.map((p,i)=>`<g class="node layer-${k}" data-layer="${k}" data-index="${i}" ${k===0?`role="button" tabindex="0" aria-label="Activate input ${i+1}" aria-pressed="false"`:''}><circle cx="${p.x}" cy="${p.y}" r="${k===0?13:7}"/><circle class="hit-area" cx="${p.x}" cy="${p.y}" r="24"/>${k===0?`<text x="${p.x}" y="${p.y+4}" text-anchor="middle">${i+1}</text>`:''}</g>`).join('')).join('');
  return `<figure class="neural-study"><div class="study-heading"><span class="eyebrow">Neural signal study</span><span class="study-number">01</span></div><svg viewBox="0 0 340 286" role="group" aria-labelledby="graph-title graph-desc"><title id="graph-title">Interactive neural network</title><desc id="graph-desc">Three inputs connect to four hidden nodes and three outputs. Activate an input to trace its signal through a fixed, illustrative network. This is not a trained model.</desc><g>${lines}</g>${nodes}<text class="layer-label" x="40" y="281" text-anchor="middle">INPUT</text><text class="layer-label" x="165" y="281" text-anchor="middle">HIDDEN</text><text class="layer-label" x="290" y="281" text-anchor="middle">OUTPUT</text></svg><figcaption><span>Hover, focus or tap an input.</span><span id="signal-status" class="signal-status" aria-live="polite">Fixed-weight illustration</span></figcaption></figure>`;
}
function projectCard(p, index) { return `<article class="work-card"><span class="index-number">${String(index+1).padStart(2,'0')}</span><div class="card-topline"><p class="eyebrow">${E(p.category)}</p>${p.period==='Ongoing'?'<span class="status">In development</span>':''}</div><h3><a href="projects.html#${p.id}">${E(p.title)}</a></h3><p class="card-subtitle">${E(p.subtitle)}</p><p>${E(p.summary)}</p>${tags(p.tags)}<a class="text-link card-link" href="projects.html#${p.id}">View project <span aria-hidden="true">↗</span></a></article>`; }
function role(r) { return `<article class="role-row"><div><h3>${E(r.title)}</h3>${r.period?`<p class="period">${E(r.period)}</p>`:''}<p class="organisation">${E(r.organisation)}</p></div><div class="role-detail"><p>${E(r.summary)}</p>${r.bullets?`<ul class="bullet-list">${r.bullets.map(b=>`<li>${E(b)}</li>`).join('')}</ul>`:''}${tags(r.tags)}</div></article>`; }
function post(p) { return `<article class="post-row"><div class="post-meta"><time datetime="${E(p.date)}">${date(p.date)}</time><span>${E(p.topic||'Notes')}</span></div><div><h2>${external(p.title,p.url)}</h2><p>${E(p.summary)}</p></div><a class="post-out" href="${safeURL(p.url)}" aria-label="Read ${E(p.title)} on LinkedIn"><span aria-hidden="true">↗</span></a></article>`; }
function layout(key, title, description, body) {
  const canonical=`https://coderalpha9.github.io/Portfolio/${key==='index'?'':`${key}.html`}`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="#F7F5EF"><title>${E(title)} | Jaiwanth Karthi</title><meta name="description" content="${E(description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${E(title)} | Jaiwanth Karthi"><meta property="og:description" content="${E(description)}"><meta property="og:url" content="${canonical}"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script></head>
<body class="page-${key}"><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="header-inner"><a class="brand" href="index.html" aria-label="Jaiwanth Karthi, home"><span class="monogram" aria-hidden="true">JK</span><span>Jaiwanth Karthi<span class="brand-caption">Engineering · IIT Madras</span></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav" hidden>Menu <span aria-hidden="true">+</span></button><nav id="primary-nav" aria-label="Main navigation">${pages.map(([k,t])=>`<a href="${k}.html"${key===k?' aria-current="page"':''}>${t}</a>`).join('')}</nav></div></header>
<main id="main" class="container">${body}</main>
<footer class="site-footer"><div class="footer-inner"><div><a class="footer-name" href="index.html">${E(profile.fullName)}</a><p>Engineering Design · IIT Madras</p></div><div class="footer-links">${social()}<a href="about.html#contact">Contact</a></div><p class="copyright">© 2026 Jaiwanth Karthi</p></div></footer></body></html>`;
}
const home = `<section class="hero"><div class="hero-copy"><p class="eyebrow">IIT Madras · Engineering Design</p><h1>Jaiwanth<br>Karthi<span class="name-stop">.</span></h1><p class="hero-focus">Machine learning & software systems</p><div class="hero-profile">${photo()}<p>${E(profile.intro)}</p></div><div class="hero-actions"><a class="button" href="projects.html">Explore my work <span aria-hidden="true">↗</span></a><a class="text-link" href="about.html">About me</a></div></div><div class="hero-aside">${graph()}<p class="aside-note">Models, inference, and the systems between.</p></div></section>
<section class="distinctions" aria-label="Selected distinctions">${awards.filter(a=>a.featured).map(a=>`<a href="achievements.html"><span class="distinction-result">${E(a.result)}</span><strong>${E(a.title)}</strong><span>${E(a.organisation)}</span></a>`).join('')}</section>
<section class="section">${sectionHead('01 / Projects','Selected work','All projects','projects.html')}<div class="work-grid">${projects.filter(p=>p.featured).map(projectCard).join('')}</div></section>
<section class="section experience-preview">${sectionHead('02 / Experience','Applied work','Experience & roles','experience.html')}<div class="experience-strip">${work.experience.map(r=>`<a href="experience.html"><p class="eyebrow">${E(r.period)}</p><h3>${E(r.organisation)}</h3><p>${E(r.title)}</p></a>`).join('')}</div></section>
<section class="section home-posts">${sectionHead('03 / Notes','Recent posts','All posts','posts.html')}${posts.slice(0,2).map(post).join('')}</section>`;
const about = `${pageHead('01','About')}<section class="about-layout"><aside class="profile-panel">${photo('about-portrait')}<h2>${E(profile.fullName)}</h2><p>${E(profile.degree)}</p><p>${E(profile.institution)}<br>${E(profile.location)}</p><div class="profile-links">${social()}</div></aside><div class="about-copy">${profile.about.map(p=>`<p>${E(p)}</p>`).join('')}<div class="focus-note"><p class="eyebrow">Primary interests</p><p>AI & deep learning, software systems, data analytics, and full-stack development.</p></div></div></section>${localNav([['education','Education'],['skills','Skills'],['certifications','Certifications'],['contact','Contact']])}
<section class="section" id="education">${sectionHead('01 / Background','Education')}<div class="record-list">${profile.education.map(r=>`<article class="record"><p class="period">${E(r.period)}</p><div><h3>${E(r.title)}</h3><p class="organisation">${E(r.organisation)}</p><p>${E(r.description)}</p></div></article>`).join('')}</div></section>
<section class="section" id="skills">${sectionHead('02 / Practice','Skills & tools')}<div class="skills-grid">${profile.skills.map(s=>`<article><h3>${E(s.title)}</h3><p>${s.items.map(E).join(' · ')}</p></article>`).join('')}</div></section>
<section class="section" id="certifications">${sectionHead('03 / Learning','Certifications')}<div class="record-list">${profile.certifications.map(c=>`<article class="record"><p class="period">${E(c.period)}</p><div><h3>${E(c.title)}</h3><p class="organisation">${E(c.organisation)}</p>${c.description?`<p>${E(c.description)}</p>`:''}</div></article>`).join('')}</div></section>
<section class="section contact-section" id="contact"><div><p class="eyebrow">04 / Contact</p><h2>Get in touch</h2></div><div class="contact-links">${profile.links.map(l=>external(l.label,l.url,'contact-link')).join('')}</div></section>`;
const achievementPage=`${pageHead('02','Achievements','Recognition across machine learning, engineering, and academic work.')}<div class="awards-list">${awards.map((a,i)=>`<article class="award${a.featured?' award-featured':''}"><div class="award-meta"><span class="award-result">${E(a.result)}</span><p class="period">${E(a.period)}</p></div><div><h2>${E(a.title)}</h2><p class="organisation">${E(a.organisation)}</p><p>${E(a.description)}</p>${media(a)}${a.url?external('Read the announcement',a.url,'text-link'):''}</div><span class="award-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span></article>`).join('')}</div>`;
const experience=`${pageHead('03','Experience','Professional work and responsibilities at IIT Madras.')}${localNav([['professional','Professional experience'],['leadership','Positions of responsibility'],['volunteering','Volunteering']])}<section class="section" id="professional">${sectionHead('01 / Industry','Professional experience')}${work.experience.map(role).join('')}</section><section class="section" id="leadership">${sectionHead('02 / Campus','Positions of responsibility')}${work.roles.map(role).join('')}</section><section class="section" id="volunteering">${sectionHead('03 / Community','Volunteering')}${work.volunteering.map(role).join('')}</section>`;
const groups=[['ai','AI & machine learning'],['systems','Software systems'],['engineering','Engineering design']];
const projectPage=`${pageHead('04','Projects','Model development, software infrastructure, and engineering experiments.')}${localNav(groups)}${groups.map(([id,category],index)=>`<section class="section" id="${id}">${sectionHead(`0${index+1} / Projects`,category)}<div class="project-list">${projects.filter(p=>p.category===category).map(p=>`<article id="${p.id}" class="project"><div class="project-heading"><div><p class="eyebrow">${E(p.subtitle)}</p><h3>${E(p.title)}</h3>${p.period?`<p class="period">${E(p.period)}</p>`:''}</div>${p.featured?'<span class="selected-label">Selected work</span>':''}</div><p class="project-summary">${E(p.summary)}</p>${p.contribution?`<p class="contribution">${E(p.contribution)}</p>`:''}${media(p)}${p.details?.length?`<details><summary>Technical notes</summary><ul class="bullet-list">${p.details.map(d=>`<li>${E(d)}</li>`).join('')}</ul></details>`:''}<div class="project-bottom">${tags(p.tags)}${p.links?.length?`<div class="project-links">${p.links.map(l=>external(l.label,l.url,'text-link')).join('')}</div>`:''}</div></article>`).join('')}</div></section>`).join('')}`;
const researchPage=`${pageHead('05','Research','Current technical work and intellectual-property projects.')}<section class="research-lead"><p class="eyebrow">Current work</p><h2>Learning architectures.<br>Efficient inference.</h2><div><p>My research-oriented work currently centres on gesture recognition and neural network optimisation. Gesturize explores how sequence models handle dynamic gestures; NanoCompile examines how trained networks can be executed more efficiently.</p><div class="inline-links"><a class="text-link" href="projects.html#gesturize">Gesturize ↗</a><a class="text-link" href="projects.html#nanocompile">NanoCompile ↗</a></div></div></section><section class="section" id="patents">${sectionHead('01 / Intellectual property','Patent work')}<p class="section-description">These projects involve ongoing patent work. They are not presented as granted patents.</p><div class="research-list">${research.patents.map(p=>`<article><p class="status">${E(p.status)}</p><h3>${E(p.title)}</h3><p>${E(p.description)}</p><a class="text-link" href="projects.html#${E(p.project)}">Related project ↗</a></article>`).join('')}</div></section>${[['publications','Publications'],['articles','Articles']].map(([key,title])=>research[key].length?`<section class="section" id="${key}">${sectionHead('Writing',title)}${research[key].map(r=>`<article class="record"><div><h3>${E(r.title)}</h3><p>${E(r.description)}</p>${r.url?external('Read',r.url,'text-link'):''}</div></article>`).join('')}</section>`:'').join('')}<section class="research-post-link"><h2>Project notes & updates</h2><a class="text-link" href="posts.html">Read posts ↗</a></section>`;
const postPage=`${pageHead('06','Posts','Project updates, competition experiences, and notes from my work.')}<div class="posts-index">${posts.map(post).join('')}</div><div class="all-posts-link">${external('View all activity on LinkedIn','https://www.linkedin.com/in/jaiwanth-karthi/recent-activity/all/','text-link')}</div>`;
const definitions=[['index','Home',profile.intro,home],['about','About','Education, technical interests, skills, and contact details for Jaiwanth Karthi.',about],['achievements','Achievements','Awards and recognition in machine learning, engineering, and academics.',achievementPage],['experience','Experience','Industry experience, project leadership, and positions of responsibility.',experience],['projects','Projects','Machine learning, software systems, and engineering projects by Jaiwanth Karthi.',projectPage],['research','Research','Ongoing work in gesture recognition, neural network optimisation, and intellectual property.',researchPage],['posts','Posts','Project notes and LinkedIn updates from Jaiwanth Karthi.',postPage],['404','Page not found','This page could not be found.',`${pageHead('404','Page not found')}<p>The address may have changed.</p><a class="button" href="/Portfolio/">Return home</a>`]];
await mkdir(root,{recursive:true});
for (const [key,title,description,body] of definitions) {
  let html=layout(key,title,description,body);
  html=html.replace('<p class="aside-note">Models, inference, and the systems between.</p>', '');
  if(key==='404') html=html.replace('<head>','<head><base href="/Portfolio/"><meta name="robots" content="noindex">');
  if (html.includes('\u2014')) throw new Error(`Em dash in ${key}`);
  await writeFile(path.join(root,`${key}.html`),html);
}
const sitemap=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(([key])=>`<url><loc>https://coderalpha9.github.io/Portfolio/${key==='index'?'':`${key}.html`}</loc></url>`).join('')}</urlset>`;
await writeFile(path.join(root,'sitemap.xml'),sitemap);
console.log(`Built ${definitions.length} pages, ${projects.length} projects, ${awards.length} achievements, ${posts.length} posts.`);
